#!/bin/sh
# Configure Mosquitto MQTT broker (runs inside the container)
# Inputs (templated):
#   {{ auth_mode }}    - Authentication mode: none, password, or certificate
#   {{ mqtt_port }}    - Port number for MQTT
#   {{ mqtts_port }}   - Port number for MQTT over TLS
#   {{ username }}     - Username for password authentication
#   {{ password }}     - Password for password authentication
#   {{ bind_address }} - IP address to bind to
#   {{ server_cert }}  - Base64-encoded server certificate content
#   {{ server_key }}   - Base64-encoded server private key content
#   {{ ca_cert }}      - Base64-encoded CA certificate content (optional, for client cert auth)
#   {{ ca_key }}       - Base64-encoded CA private key content (optional, for client cert auth)
set -eu

AUTH_MODE="{{ auth_mode }}"
MQTT_PORT="{{ mqtt_port }}"
MQTTS_PORT="{{ mqtts_port }}"
USERNAME="{{ username }}"
PASSWORD="{{ password }}"
BIND_ADDRESS="{{ bind_address }}"
SERVER_CERT="{{ server_cert }}"
SERVER_KEY="{{ server_key }}"
CA_CERT="{{ ca_cert }}"
CA_KEY="{{ ca_key }}"

MOSQUITTO_CONF="/etc/mosquitto/mosquitto.conf"
PASSWORD_FILE="/etc/mosquitto/passwd"
CERTS_DIR="/etc/mosquitto/certs"

# Ensure mosquitto configuration directory exists
mkdir -p /etc/mosquitto >&2
chown -R mosquitto:mosquitto /etc/mosquitto >&2

# Create basic configuration file
cat > "$MOSQUITTO_CONF" << 'EOF'
# Mosquitto MQTT Broker Configuration
# Generated by lxc-manager

# General settings
pid_file /var/run/mosquitto.pid
user mosquitto

# Persistence
persistence true
persistence_location /var/lib/mosquitto/

# Logging
log_dest file /var/log/mosquitto/mosquitto.log
log_type all
log_timestamp true

# Connection settings
max_connections -1
max_inflight_messages 20
max_queued_messages 1000

# Message settings
message_size_limit 0
retained_persistence true
autosave_interval 300
EOF

# Configure listeners based on authentication mode
if [ "$AUTH_MODE" = "none" ]; then
  # No authentication - allow anonymous connections on MQTT port
  cat >> "$MOSQUITTO_CONF" << EOF

# Listener on MQTT port (no authentication)
listener ${MQTT_PORT} ${BIND_ADDRESS}
allow_anonymous true
EOF
  echo "Configured Mosquitto with no authentication on port ${MQTT_PORT}" >&2

elif [ "$AUTH_MODE" = "password" ]; then
  # Password authentication
  if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
    echo "Error: Username and password are required for password authentication mode" >&2
    exit 1
  fi

  # Create password file
  if [ -f "$PASSWORD_FILE" ]; then
    rm -f "$PASSWORD_FILE" >&2
  fi

  # Create password file with username/password
  # mosquitto_passwd uses stdin for password input
  echo "$PASSWORD" | mosquitto_passwd -c -b "$PASSWORD_FILE" "$USERNAME" >&2

  # Set proper permissions
  chown mosquitto:mosquitto "$PASSWORD_FILE" >&2
  chmod 600 "$PASSWORD_FILE" >&2

  cat >> "$MOSQUITTO_CONF" << EOF

# Listener on MQTT port (password authentication)
listener ${MQTT_PORT} ${BIND_ADDRESS}
allow_anonymous false
password_file ${PASSWORD_FILE}
EOF
  echo "Configured Mosquitto with password authentication on port ${MQTT_PORT}" >&2

elif [ "$AUTH_MODE" = "certificate" ]; then
  # TLS with optional client certificate authentication
  mkdir -p "$CERTS_DIR" >&2
  chown mosquitto:mosquitto "$CERTS_DIR" >&2
  chmod 700 "$CERTS_DIR" >&2

  HAS_CA=false

  # Handle CA certificate - optional, only for client cert auth
  if [ -n "$CA_CERT" ]; then
    echo "Using uploaded CA certificate for client authentication" >&2
    echo "$CA_CERT" | base64 -d > "$CERTS_DIR/ca.crt" >&2
    if [ -n "$CA_KEY" ]; then
      echo "$CA_KEY" | base64 -d > "$CERTS_DIR/ca.key" >&2
      HAS_CA=true
    else
      echo "Error: CA certificate provided but CA key is missing" >&2
      exit 1
    fi
    chown mosquitto:mosquitto "$CERTS_DIR/ca.crt" "$CERTS_DIR/ca.key" >&2
    chmod 644 "$CERTS_DIR/ca.crt" >&2
    chmod 600 "$CERTS_DIR/ca.key" >&2
  fi

  # Handle server certificate - use uploaded or generate
  if [ -n "$SERVER_CERT" ]; then
    echo "Using uploaded server certificate" >&2
    echo "$SERVER_CERT" | base64 -d > "$CERTS_DIR/server.crt" >&2
    if [ -n "$SERVER_KEY" ]; then
      echo "$SERVER_KEY" | base64 -d > "$CERTS_DIR/server.key" >&2
    else
      echo "Error: Server certificate provided but server key is missing" >&2
      exit 1
    fi
    chown mosquitto:mosquitto "$CERTS_DIR/server.crt" "$CERTS_DIR/server.key" >&2
    chmod 644 "$CERTS_DIR/server.crt" >&2
    chmod 600 "$CERTS_DIR/server.key" >&2
  else
    # Generate server certificate
    if [ "$HAS_CA" = "true" ]; then
      # Generate server certificate signed by CA
      echo "Generating server certificate signed by CA..." >&2
      openssl genrsa -out "$CERTS_DIR/server.key" 2048 >&2
      openssl req -new -key "$CERTS_DIR/server.key" -out "$CERTS_DIR/server.csr" \
        -subj "/CN=MQTT Server" >&2
      openssl x509 -req -in "$CERTS_DIR/server.csr" -CA "$CERTS_DIR/ca.crt" \
        -CAkey "$CERTS_DIR/ca.key" -CAcreateserial -out "$CERTS_DIR/server.crt" \
        -days 3650 >&2
      rm -f "$CERTS_DIR/server.csr" >&2
    else
      # Generate self-signed server certificate
      echo "Generating self-signed server certificate..." >&2
      openssl req -x509 -newkey rsa:2048 -keyout "$CERTS_DIR/server.key" \
        -out "$CERTS_DIR/server.crt" -days 3650 -nodes \
        -subj "/CN=MQTT Server" >&2
    fi
    chown mosquitto:mosquitto "$CERTS_DIR/server.key" "$CERTS_DIR/server.crt" >&2
    chmod 600 "$CERTS_DIR/server.key" >&2
    chmod 644 "$CERTS_DIR/server.crt" >&2
    echo "Server certificate generated at ${CERTS_DIR}/server.crt" >&2
  fi

  # Configure TLS listener
  cat >> "$MOSQUITTO_CONF" << EOF

# Listener on MQTTS port (TLS)
listener ${MQTTS_PORT} ${BIND_ADDRESS}
protocol mqtt
certfile ${CERTS_DIR}/server.crt
keyfile ${CERTS_DIR}/server.key
EOF

  # Add CA and client certificate requirements only if CA is provided
  if [ "$HAS_CA" = "true" ]; then
    cat >> "$MOSQUITTO_CONF" << EOF
cafile ${CERTS_DIR}/ca.crt
require_certificate true
use_identity_as_username true
allow_anonymous false
EOF
    echo "Configured Mosquitto with TLS and client certificate authentication on port ${MQTTS_PORT}" >&2
  else
    cat >> "$MOSQUITTO_CONF" << EOF
allow_anonymous true
EOF
    echo "Configured Mosquitto with TLS (no client certificate required) on port ${MQTTS_PORT}" >&2
  fi

else
  echo "Error: Invalid authentication mode: ${AUTH_MODE}" >&2
  echo "Valid modes are: none, password, certificate" >&2
  exit 1
fi

# Ensure log directory exists
mkdir -p /var/log/mosquitto >&2
chown mosquitto:mosquitto /var/log/mosquitto >&2

# Ensure data directory exists
mkdir -p /var/lib/mosquitto >&2
chown mosquitto:mosquitto /var/lib/mosquitto >&2

echo "Mosquitto configuration completed successfully" >&2
exit 0
